server:
  port: 8888
  error:
    include-message: always

spring:
  application:
    name: userAuth-app
  datasource:
    url: jdbc:mysql://localhost:3306/userAuth_db?createDatabaseIfNotExist=true
    username: root
    password: root@072023
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
