server:
  port: 9090

spring:
  data:
    mongodb:
      database: moviesdb
      uri: mongodb://localhost:27017
  application:
    name: movie-app
  mvc:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET, POST, PUT, DELETE
      allow-credentials: true
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
